spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhiye?useUnicode=true&characterEncoding=utf-8&useSSL=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
server:
  context-path: /zhiye